"""remove project layer

Revision ID: 068c1ae43e5f
Revises: ab51d02cb858
Create Date: 2024-05-18 09:03:14.982249+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '068c1ae43e5f'
down_revision: Union[str, None] = 'ab51d02cb858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_row_id', sa.Integer(), nullable=False),
    sa.Column('executed_operation', sa.Integer(), nullable=False),
    sa.Column('operation_executed_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_after_executed_operation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('from_undo', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('last_modifier_id', sa.Integer(), nullable=False),
    sa.Column('from_undo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['last_modifier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_project')
    op.drop_table('project')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('project_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='project_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_project',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='user_project_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_project_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'project_id', name='user_project_pkey')
    )
    op.drop_table('task')
    op.drop_table('h_task')
    # ### end Alembic commands ###
