"""add used marker in h_task

Revision ID: 6c41dc7e9a66
Revises: 0e3edbd17f92
Create Date: 2024-05-19 12:09:05.627957+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6c41dc7e9a66'
down_revision: Union[str, None] = '0e3edbd17f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'h_task',
        sa.Column('used',
                  sa.Boolean(),
                  server_default=sa.text('false'),
                  nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('h_task', 'used')
    # ### end Alembic commands ###
