"""reset

Revision ID: 95be198e6456
Revises: 
Create Date: 2024-05-18 18:00:19.962542+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95be198e6456'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=128), nullable=False),
        sa.Column('password_hash', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('username'))
    op.create_table(
        'h_task', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('target_row_id', sa.String(), nullable=False),
        sa.Column('executed_operation', sa.Integer(), nullable=False),
        sa.Column('operation_executed_at',
                  sa.TIMESTAMP(),
                  server_default=sa.text('now()'),
                  nullable=False),
        sa.Column('data_after_executed_operation',
                  postgresql.JSONB(astext_type=sa.Text()),
                  nullable=True),
        sa.Column('from_undo', sa.Boolean(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'task', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=64), nullable=False),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.Column('last_modifier_id', sa.Integer(), nullable=False),
        sa.Column('from_undo', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['creator_id'],
            ['user.id'],
        ), sa.ForeignKeyConstraint(
            ['last_modifier_id'],
            ['user.id'],
        ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('h_task')
    op.drop_table('user')
    # ### end Alembic commands ###
