"""cascade delete

Revision ID: a8fd9bfd02ca
Revises: 0f7a254539ba
Create Date: 2024-05-17 07:55:13.296152+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fd9bfd02ca'
down_revision: Union[str, None] = '0f7a254539ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_project_project_id_fkey', 'user_project', type_='foreignkey')
    op.create_foreign_key(None, 'user_project', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project', type_='foreignkey')
    op.create_foreign_key('user_project_project_id_fkey', 'user_project', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
