"""to date

Revision ID: e5fd722882aa
Revises: 95be198e6456
Create Date: 2024-05-18 18:46:25.258001+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5fd722882aa'
down_revision: Union[str, None] = '95be198e6456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'due_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
                existing_nullable=True)
    # ### end Alembic commands ###
